# Day 13
## Puzzle 1

In [163]:
import numpy as np
from numpy.linalg import LinAlgError
import re

In [164]:
input_file = 'input_1.txt'
# input_file = 'test_input_1.txt'

Read the game input equations.

In [165]:
with open(file=input_file, mode="r") as file:
    game_equations = []
    text = file.read()
    
    for game in text.split('\n\n'):  # Each game is separated by a blank line.
        values = re.findall(r'[-+]?(?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d+)?', game)  # Extract the numbers and the signs (I don't think negative numbers will show up, but still...)
        formatted_values = []
        
        for value in values:
            if value.startswith('+'):
                formatted_values.append(int(value.split('+')[-1]))

            elif value.startswith('-'):
                formatted_values.append(-int(value.split('-')[-1]))

            else:
                formatted_values.append(int(value))

        a_button = np.array(formatted_values[:2])
        b_button = np.array(formatted_values[2:4])
        A = np.matrix([a_button, b_button]).T  # Coefficient A matrix of the linear equation Ax = b.
        prize = np.array(formatted_values[4:])  # Right-hand side vector b of the linear equation Ax = b.
        game_equations.append([A, prize])


In [166]:
game_equations[:10]

[[matrix([[49, 35],
          [27, 65]]),
  array([4326, 4898])],
 [matrix([[82, 20],
          [64, 67]]),
  array([ 6818, 10409])],
 [matrix([[75, 95],
          [72, 15]]),
  array([8360, 4749])],
 [matrix([[59, 15],
          [26, 29]]),
  array([7401, 3032])],
 [matrix([[77, 15],
          [38, 46]]),
  array([13582, 10664])],
 [matrix([[39, 27],
          [11, 40]]),
  array([1367, 2880])],
 [matrix([[50, 20],
          [28, 55]]),
  array([7220,  383])],
 [matrix([[63, 21],
          [63, 97]]),
  array([ 4200, 10964])],
 [matrix([[60, 13],
          [31, 52]]),
  array([5226, 4907])],
 [matrix([[13, 84],
          [96, 22]]),
  array([ 7154, 10948])]]

For each game, we now solve the linear equation system $A\vec{x}=\vec{b}$. The first column of $A$ represent pressing button "A", and the second column of $A$ represents pressing the button "B". The elements of the solution vector $\vec{x}$ represents the number of times we need to press the buttons in order to get the values in the prize vector $\vec{b}$. If no solution exists, we continue to the next game. Also, the values of $\vec{x}$ must all be integers and non-negative. All solution vectors are multiplied by the token cost vector $\begin{pmatrix} 3 & 1 \end{pmatrix}$ and the result is added to the total to get the final result.

In [167]:
tokens_needed = 0

for game_equation in game_equations:
    try:
        solution = np.linalg.solve(game_equation[0], game_equation[1])

    except LinAlgError:
        print('No solution exists for this equation!')
        continue

    token_cost = np.array([3, 1])  # Cost for pressing buttons "A" and "B".
    tolerance = 0.0001
    integer_solution = all(abs(val - round(val)) <= tolerance for val in solution)  # We consider values within a certain tolerance as integers.
    non_negative_solution = all(solution >= 0)  # All values must be non-negative.

    if integer_solution and non_negative_solution:
        tokens_needed += solution@token_cost

In [168]:
int(tokens_needed)

36250

## Puzzle 2

This time, the only difference from part one is that we add the vector $10^{13} \begin{pmatrix} 1 & 1 \end{pmatrix}$ to the price vector $\vec{b}$ before solving.

In [169]:
tokens_needed = 0

for game_equation in game_equations:
    updated_prize = game_equation[1] + 10**13*np.array([1, 1])

    try:
        solution = np.linalg.solve(game_equation[0], updated_prize)

    except LinAlgError:
        print('No solution exists for this equation!')
        continue

    token_cost = np.array([3, 1])
    tolerance = 0.0001
    integer_solution = all(abs(val - round(val)) <= tolerance for val in solution)
    non_negative_solution = all(solution >= 0)

    if integer_solution and non_negative_solution:
        tokens_needed += solution@token_cost

In [170]:
int(tokens_needed)

83232379451012